# Generated by Django 5.0.6 on 2024-05-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='V2NModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes_title', models.CharField(max_length=200)),
                ('notes_content', models.CharField(max_length=1000)),
            ],
        ),
    ]
